paths_to_2d_data = ['C:\\Users\\dongq\\DeepLabCut\\Test-Qiwei-2020-11-23\\videos\\Han_20201123_test_5in00001DLC_resnet50_TestNov23shuffle1_1030000filtered.csv',
'C:\\Users\\dongq\\DeepLabCut\\Test-Qiwei-2020-11-23\\videos\\Han_20201123_test_5in00002DLC_resnet50_TestNov23shuffle1_1030000filtered.csv']

path_to_save_static_data = 'C:\Users\dongq\DeepLabCut\Test-Qiwei-2020-11-23\static-data-5in'

output_video_path = 'C:\Users\dongq\DeepLabCut\Test-Qiwei-2020-11-23\reconsturcted-3d-data-5in'

[video]
fps = 25
resolution = [1280, 1024]

[calibration]
# checkerboard / charuco / aruco
board_type = 'charuco'

# width and height of grid
board_size = [5, 7]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 6

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

# length of marker side
board_marker_length = 23.17 # mm

# If aruco, length of marker separation
# board_marker_separation_length = 2.78 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 38.43 # mm

calib_video_path = 'C:\Users\dongq\DeepLabCut\Test-Qiwei-2020-11-23\calibration-video-5in'
calib_video_prefix = 'Han_20201123_calib_5in0000'
video_extension = 'avi'


[triangulation]
axes = [
    ["y", "pointX", "pointY"], 
    ["z", "pointX", "pointZ"]]

reference_point = "pointX"
cam_align = "1"
reconstruction_threshold = 0.7
reconstruction_output_path = 'C:\Users\dongq\DeepLabCut\Test-Qiwei-2020-11-23\reconsturcted-3d-data'

[labeling]
scheme = [
  ["shoulder1", "arm1"],
  ["shoulder1", "elbow2"],
  ["arm1", "arm2"],
  ["arm2", "elbow2"],
  ["elbow1", "wrist1"],
  ["elbow2", "wrist2"],
  ["wrist1", "hand1"],
  ["wrist2", "hand3"],
  ["hand1", "hand2"],
  ["hand3", "hand2"],
  ["pointX", "pointY"],
  ["pointX", "pointZ"]]

bodyparts_interested = ['shoulder1', 'arm1', 'arm2', 'elbow1', 'elbow2', 'wrist1', 
          'wrist2', 'hand1', 'hand2', 'hand3',
          'pointX', 'pointY', 'pointZ']
