function [ prop ] = getMuscleSpindleProportions(musc_len, musc_names)

max_force_list = {'abd_poll_longus',30;...
    'flex_carpi_ulnaris',96;...
    'flex_digit_profundus',30;...
    'flex_digit_superficialis',30;...
    'flex_poll_longus',30;...
    'palmaris_longus',27;...
    'ext_carp_rad_brevis',30;...
    'ext_carpi_rad_longus',72;...
    'ext_digiti',30;...
    'ext_digitorum',30;...
    'ext_indicis',30;...
    'flex_carpi_radialis',60;...
    'anconeus',30;...
    'dorsoepitrochlearis',44.8;...
    'tricep_lat',135.6;...
    'tricep_lon',116.1;...
    'tricep_sho',135.6;...
    'bicep_lh',58.2;...
    'deltoid_ant',135.6;...
    'deltoid_med',116.1;...
    'deltoid_pos',406.5;...
    'supraspinatus',135;...
    'bicep_sh',38.7;...
    'coracobrachialis',38.7;...
    'pectoralis_inf',116.1;...
    'pectoralis_sup',154.8;...
    'brachialis',135.6;...
    'brachioradialis',38.7;...
    'pronator_teres',48.3;...
    'supinator',30;...
    'lat_dorsi_cen',129;...
    'lat_dorsi_inf',129;...
    'lat_dorsi_sup',129;...
    'teres_major',77.4;...
    'pronator_quad',33.3;...
    'subscapularis',290.4;...
    'teres_minor',174;...
    'ext_carpi_ulnaris',30;...
    'infraspinatus',174.3};

    spind_count = zeros(numel(musc_len),1);
    for i_musc = 1:numel(musc_len)
        % for each muscle, get force from list.
        force_idx = find(strcmpi(erase(musc_names{i_musc},'_len'),max_force_list(:,1)),1,'first');
        force_val = max_force_list{force_idx,2};
        % compute spindle count as sqrt(len*max_force)
        spind_count(i_musc) = sqrt(force_val*musc_len(i_musc));
        
    end
    % return spindle count as a proportion across muscles
    prop = spind_count/sum(spind_count);
end

