function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 15-May-2017 19:28:54

persistent Hd;

if isempty(Hd)
    
    delay = 1e-05;  % Fractional Delay
    N     = 5;      % Order
    Fs    = 30000;  % Sampling Frequency
    
    h = fdesign.fracdelay(delay, 'n', N, Fs);
    
    Hd = design(h, 'lagrange');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

